apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "dapr-components.labels" . | nindent 4 }}
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []

scopes:
  - {{ .Values.apps.backend }}
  - {{ .Values.apps.recurring }}
  - {{ .Values.apps.notification }}
