{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: todo-app
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOlFpciU0MHVfUzJlZWQxMjNAcG9zdGdyZXM6NTQzMi9hcHA=
{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: todo-app
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOlFpciU0MHVfUzJlZWQxMjNAcG9zdGdyZXM6NTQzMi9hcHA=
  OPENAI_API_KEY: QUl6YVN5QlJWNlpfUHlvNVQ1ZGxrbXVEZGNOWVVxbWpraXlzcjVz
{{- end }}

{{- end }}
