# Dapr Pub/Sub Component for Kafka (Docker Compose)
# This component enables event-driven messaging via Kafka topics
# Used for: task-events, reminders, task-updates topics

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    # Kafka broker address for Docker Compose
    - name: brokers
      value: "kafka:9092"

    # Consumer group for this application
    - name: consumerGroup
      value: "taskflow-consumer-group"

    # Client ID
    - name: clientID
      value: "todo-app"

    # Authentication (none for local development)
    - name: authType
      value: "none"

    # Topic configuration
    - name: initialOffset
      value: "newest"

    # Disable automatic topic creation (we'll create them manually)
    - name: disableTopicCreation
      value: "false"

    # Allow auto-creation for development
    - name: autoCreateTopic
      value: "true"

# Scopes define which applications can use this component
scopes:
  - backend-api
  - recurring-task-service
  - notification-service
