# Dapr Secrets Management Component for Kubernetes Secrets
# This component provides access to Kubernetes secrets for credential management
# Used for: Gemini API key, database credentials, Kafka credentials

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: todo-app
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
  # No metadata required - uses cluster's service account
  # Dapr automatically reads secrets from the cluster

# Secrets are referenced in application configuration as:
# ${kubernetes-secret-name} or {secret-name.key}

# Example Kubernetes secrets that should be created:
# apiVersion: v1
# kind: Secret
# metadata:
#   name: taskflow-secrets
#   namespace: todo-app
# type: Opaque
# stringData:
#   gemini-api-key: "your-gemini-api-key"
#   database-connection-string: "postgresql://user:pass@host:5432/db"
#   redpanda-bootstrap-servers: "cluster-id.redpanda.cloud:9092"
#   redpanda-username: "api-key-id"
#   redpanda-password: "api-key-secret"

# Usage in Dapr components:
# metadata:
#   - name: apiKey
#     secretKeyRef:
#       name: taskflow-secrets
#       key: gemini-api-key

# Scopes define which applications can use this component
scopes:
  - backend-api
  - recurring-task-service
  - notification-service
  - audit-service
